preprocess:
  input: data/data.csv
  output: artifact/processed/data.csv

train:
  data: artifact/processed/data.csv
  model: artifact/model/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5
  